services:
  db:
    container_name: postgreSQL-meow
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4-meow
    image: dpage/pgadmin4:8.13
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5051:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  bot:
    container_name: meow-bot
    image: meow-bot:1
    restart: always
    volumes:
      - ./data:/usr/src/meowBot/data

volumes:
  pgdata:
    name: meow_docker_pgdata
  pgadmin:
    name: meow_docker_pgadmin